experiment w/token

diff --git a/.github/workflows/resource-warning.yml b/.github/workflows/resource-warning.yml
--- a/.github/workflows/resource-warning.yml
+++ b/.github/workflows/resource-warning.yml
@@ -17,14 +17,18 @@ jobs:
         run: |
           mkdir -p logs/baseline
           for machine in hera gaeac6 ursa orion hercules derecho wcoss2 acorn; do
-            curl -sSf -o logs/baseline/RegressionTests_${machine}.log \
-              https://raw.githubusercontent.com/ufs-community/ufs-weather-model/develop/tests/logs/RegressionTests_${machine}.log || echo "Missing baseline for $machine"
+            curl -sSfL -o logs/baseline/RegressionTests_${machine}.log \
+            -H "Accept: application/vnd.github.object" \
+            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            https://api.github.com/repos/ufs-community/ufs-weather-model/contents/tests/logs/RegressionTests_${machine}.log \
+            || echo "Missing baseline for $machine"
           done
 
       - name: Compare logs and collect warnings
         run: |
           mkdir -p logs/feature
-          python scripts/collect_updated_warnings.py logs/feature/ logs/baseline/ summary.md
+          python tests/ci/scripts/collect_updated_warnings.py logs/feature/ logs/baseline/ summary.md
 
       - name: Post summary to PR
         if: github.event_name == 'pull_request'
